document.writeln("<!DOCTYPE html>");
document.writeln("<html lang=\'en\'>");
document.writeln("<head>");
document.writeln("    <meta charset=\'UTF-8\'>");
document.writeln("    <title>轮播图</title>");
document.writeln("    <script type=\'text/javascript\' src=\'../plugins/jquery/js/jquery-3.3.1.js\'></script>");
document.writeln("    <style type=\'text/css\'>");
document.writeln("        * {");
document.writeln("");
document.writeln("            padding: 0px;");
document.writeln("");
document.writeln("            margin: 0px;");
document.writeln("");
document.writeln("        }");
document.writeln("");
document.writeln("        a {");
document.writeln("");
document.writeln("            text-decoration: none;");
document.writeln("");
document.writeln("        }");
document.writeln("");
document.writeln("        ul {");
document.writeln("");
document.writeln("            list-style: outside none none;");
document.writeln("");
document.writeln("        }");
document.writeln("");
document.writeln("        .slider, .slider-panel img, .slider-extra {");
document.writeln("");
document.writeln("            width: 100%;");
document.writeln("");
document.writeln("            height: 413px;");
document.writeln("");
document.writeln("        }");
document.writeln("");
document.writeln("        .slider {");
document.writeln("");
document.writeln("            text-align: center;");
document.writeln("");
document.writeln("            margin: 30px auto;");
document.writeln("");
document.writeln("            position: relative;");
document.writeln("");
document.writeln("        }");
document.writeln("");
document.writeln("        .slider-panel, .slider-nav, .slider-pre, .slider-next {");
document.writeln("");
document.writeln("            position: absolute;");
document.writeln("");
document.writeln("            z-index: 8;");
document.writeln("");
document.writeln("        }");
document.writeln("");
document.writeln("        .slider-panel {");
document.writeln("");
document.writeln("            position: absolute;");
document.writeln("");
document.writeln("        }");
document.writeln("");
document.writeln("        .slider-panel img {");
document.writeln("");
document.writeln("            border: none;");
document.writeln("");
document.writeln("        }");
document.writeln("");
document.writeln("        .slider-extra {");
document.writeln("");
document.writeln("            position: relative;");
document.writeln("");
document.writeln("        }");
document.writeln("");
document.writeln("        .slider-nav {");
document.writeln("");
document.writeln("            margin-left: -51px;");
document.writeln("");
document.writeln("            position: absolute;");
document.writeln("");
document.writeln("            left: 50%;");
document.writeln("");
document.writeln("            bottom: 4px;");
document.writeln("");
document.writeln("        }");
document.writeln("");
document.writeln("        .slider-nav li {");
document.writeln("");
document.writeln("            background: #FFF;");
document.writeln("");
document.writeln("            border-radius: 50%;");
document.writeln("");
document.writeln("            color: #999;");
document.writeln("");
document.writeln("            cursor: pointer;");
document.writeln("");
document.writeln("            margin: 0 2px;");
document.writeln("");
document.writeln("            overflow: hidden;");
document.writeln("");
document.writeln("            text-align: center;");
document.writeln("");
document.writeln("            display: inline-block;");
document.writeln("");
document.writeln("            height: 18px;");
document.writeln("");
document.writeln("            line-height: 18px;");
document.writeln("");
document.writeln("            width: 18px;");
document.writeln("");
document.writeln("        }");
document.writeln("");
document.writeln("        .slider-nav .slider-item-selected {");
document.writeln("");
document.writeln("            background: #F00;");
document.writeln("");
document.writeln("        }");
document.writeln("");
document.writeln("        .slider-page a{");
document.writeln("");
document.writeln("            background: rgba(0, 0, 0, 0.2);");
document.writeln("");
document.writeln("            filter: progid:DXImageTransform.Microsoft.gradient(startColorstr=#33000000,endColorstr=#33000000);");
document.writeln("");
document.writeln("            color: #fff;");
document.writeln("");
document.writeln("            text-align: center;");
document.writeln("");
document.writeln("            display: block;");
document.writeln("");
document.writeln("            font-family: \'simsun\';");
document.writeln("");
document.writeln("            font-size: 22px;");
document.writeln("");
document.writeln("            width: 28px;");
document.writeln("");
document.writeln("            height: 62px;");
document.writeln("");
document.writeln("            line-height: 62px;");
document.writeln("");
document.writeln("            margin-top: -31px;");
document.writeln("");
document.writeln("            position: absolute;");
document.writeln("");
document.writeln("            top: 50%;");
document.writeln("");
document.writeln("        }");
document.writeln("");
document.writeln("        .slider-page a:HOVER {");
document.writeln("");
document.writeln("            background: rgba(0, 0, 0, 0.4);");
document.writeln("");
document.writeln("            filter: progid:DXImageTransform.Microsoft.gradient(startColorstr=#66000000,endColorstr=#66000000);");
document.writeln("");
document.writeln("        }");
document.writeln("");
document.writeln("        .slider-next {");
document.writeln("");
document.writeln("            left: 100%;");
document.writeln("");
document.writeln("            margin-left: -28px;");
document.writeln("");
document.writeln("        }");
document.writeln("    </style>");
document.writeln("");
document.writeln("    <script>");
document.writeln("        /*$(document).ready(function() */");
document.writeln("        $(function () {");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("            var length,");
document.writeln("");
document.writeln("                currentIndex = 0,");
document.writeln("");
document.writeln("                interval,");
document.writeln("");
document.writeln("                hasStarted = false, //是否已经开始轮播");
document.writeln("");
document.writeln("                t = 3000; //轮播时间间隔");
document.writeln("");
document.writeln("            length = $(\'.slider-panel\').length;");
document.writeln("");
document.writeln("            //将除了第一张图片隐藏");
document.writeln("");
document.writeln("            $(\'.slider-panel:not(:first)\').hide();");
document.writeln("");
document.writeln("            //将第一个slider-item设为激活状态");
document.writeln("");
document.writeln("            $(\'.slider-item:first\').addClass(\'slider-item-selected\');");
document.writeln("");
document.writeln("            //隐藏向前、向后翻按钮");
document.writeln("");
document.writeln("            $(\'.slider-page\').hide();");
document.writeln("");
document.writeln("            //鼠标上悬时显示向前、向后翻按钮,停止滑动，鼠标离开时隐藏向前、向后翻按钮，开始滑动");
document.writeln("");
document.writeln("            $(\'.slider-panel, .slider-pre, .slider-next\').hover(function() {");
document.writeln("");
document.writeln("                stop();");
document.writeln("");
document.writeln("                $(\'.slider-page\').show();");
document.writeln("");
document.writeln("            }, function() {");
document.writeln("");
document.writeln("                $(\'.slider-page\').hide();");
document.writeln("");
document.writeln("                start();");
document.writeln("");
document.writeln("            });");
document.writeln("");
document.writeln("            $(\'.slider-item\').hover(function(e) {");
document.writeln("");
document.writeln("                stop();");
document.writeln("");
document.writeln("                var preIndex = $(\'.slider-item\').filter(\'.slider-item-selected\').index();");
document.writeln("");
document.writeln("                currentIndex = $(this).index();");
document.writeln("");
document.writeln("                play(preIndex, currentIndex);");
document.writeln("");
document.writeln("            }, function() {");
document.writeln("");
document.writeln("                start();");
document.writeln("");
document.writeln("            });");
document.writeln("");
document.writeln("            $(\'.slider-pre\').unbind(\'click\');");
document.writeln("");
document.writeln("            $(\'.slider-pre\').bind(\'click\', function() {");
document.writeln("");
document.writeln("                pre();");
document.writeln("");
document.writeln("            });");
document.writeln("");
document.writeln("            $(\'.slider-next\').unbind(\'click\');");
document.writeln("");
document.writeln("            $(\'.slider-next\').bind(\'click\', function() {");
document.writeln("");
document.writeln("                next();");
document.writeln("");
document.writeln("            });");
document.writeln("");
document.writeln("            /**");
document.writeln("");
document.writeln("             * 向前翻页");
document.writeln("");
document.writeln("             */");
document.writeln("");
document.writeln("            function pre() {");
document.writeln("");
document.writeln("                var preIndex = currentIndex;");
document.writeln("");
document.writeln("                currentIndex = (--currentIndex + length) % length;");
document.writeln("");
document.writeln("                play(preIndex, currentIndex);");
document.writeln("");
document.writeln("            }");
document.writeln("");
document.writeln("            /**");
document.writeln("");
document.writeln("             * 向后翻页");
document.writeln("");
document.writeln("             */");
document.writeln("");
document.writeln("            function next() {");
document.writeln("");
document.writeln("                var preIndex = currentIndex;");
document.writeln("");
document.writeln("                currentIndex = ++currentIndex % length;");
document.writeln("");
document.writeln("                play(preIndex, currentIndex);");
document.writeln("");
document.writeln("            }");
document.writeln("");
document.writeln("            /**");
document.writeln("");
document.writeln("             * 从preIndex页翻到currentIndex页");
document.writeln("");
document.writeln("             * preIndex 整数，翻页的起始页");
document.writeln("");
document.writeln("             * currentIndex 整数，翻到的那页");
document.writeln("");
document.writeln("             */");
document.writeln("");
document.writeln("            function play(preIndex, currentIndex) {");
document.writeln("");
document.writeln("                $(\'.slider-panel\').eq(preIndex).fadeOut(500)");
document.writeln("");
document.writeln("                    .parent().children().eq(currentIndex).fadeIn(1000);");
document.writeln("");
document.writeln("                $(\'.slider-item\').removeClass(\'slider-item-selected\');");
document.writeln("");
document.writeln("                $(\'.slider-item\').eq(currentIndex).addClass(\'slider-item-selected\');");
document.writeln("");
document.writeln("            }");
document.writeln("");
document.writeln("            /**");
document.writeln("");
document.writeln("             * 开始轮播");
document.writeln("");
document.writeln("             */");
document.writeln("");
document.writeln("            function start() {");
document.writeln("");
document.writeln("                if(!hasStarted) {");
document.writeln("");
document.writeln("                    hasStarted = true;");
document.writeln("");
document.writeln("                    interval = setInterval(next, t);");
document.writeln("");
document.writeln("                }");
document.writeln("");
document.writeln("            }");
document.writeln("");
document.writeln("            /**");
document.writeln("");
document.writeln("             * 停止轮播");
document.writeln("");
document.writeln("             */");
document.writeln("");
document.writeln("            function stop() {");
document.writeln("");
document.writeln("                clearInterval(interval);");
document.writeln("");
document.writeln("                hasStarted = false;");
document.writeln("");
document.writeln("            }");
document.writeln("");
document.writeln("            //开始轮播");
document.writeln("");
document.writeln("            start();");
document.writeln("");
document.writeln("        });");
document.writeln("    </script>");
document.writeln("</head>");