document.writeln("<!DOCTYPE html>");
document.writeln("<html lang=\'en\'>");
document.writeln("<head>");
document.writeln("    <meta charset=\'UTF-8\'>");
document.writeln("    <title>用户登录</title>");
document.writeln("    <link rel=\'stylesheet\' href=\'../css/main.css\'/>");
document.writeln("    <link rel=\'stylesheet\' href=\'../css/index.css\'/>");
document.writeln("    <script type=\'text/javascript\' src=\'../plugins/jquery/js/jquery-3.3.1.js\'></script>");
document.writeln("    <script>");
document.writeln("        $(function () {");
document.writeln("");
document.writeln("            //查询添加功能导航菜单");
document.writeln("            $.ajax({");
document.writeln("                url: \'/nav/findNavAll\',");
document.writeln("                type: \'get\',");
document.writeln("                dataType: \'json\',");
document.writeln("                success: function (data) {");
document.writeln("                    for (var i = 0; i < data.length; i++) {");
document.writeln("                        $(\'.navUl\').append(\'<li><a href=\' + data[i].url + \'>\' + data[i].cname + \'</a></li>\')");
document.writeln("                    }");
document.writeln("                }");
document.writeln("            });");
document.writeln("        });");
document.writeln("    </script>");
document.writeln("</head>");
document.writeln("");
document.writeln("<body>");
document.writeln("<!-- 头部栏 -->");
document.writeln("<header class=\'clearfix\'>");
document.writeln("    <!-- 头部文字 -->");
document.writeln("    <div class=\'header\'>");
document.writeln("        <div class=\'container\'>");
document.writeln("            <p>您好，欢迎来到疯游精旅游网！");
document.writeln("                <a href=\'../html/login.html\'>登录</a>");
document.writeln("                <a href=\'../html/register.html\'>注册</a>");
document.writeln("            </p>");
document.writeln("            <ul>");
document.writeln("                <li>");
document.writeln("                    <a href=\'#\'>个人中心</a>");
document.writeln("                </li>");
document.writeln("                <li>");
document.writeln("                    <a href=\'#\'>给管理员留言</a>");
document.writeln("                </li>");
document.writeln("            </ul>");
document.writeln("        </div>");
document.writeln("    </div>");
document.writeln("    <!-- 头部栏下半部 -->");
document.writeln("    <div class=\'header-down container\'>");
document.writeln("        <img src=\'../img/header-img_03.gif\'/>");
document.writeln("        <div class=\'phone\'>");
document.writeln("            <img src=\'../img/phone_06.gif\'/>");
document.writeln("            <p>客户服务热线</p><br/>");
document.writeln("            <i><span>0571-</span>87166902</i>");
document.writeln("        </div>");
document.writeln("        <div class=\'search\'>");
document.writeln("            <form action=\'#\'>");
document.writeln("                <select>");
document.writeln("                    <option value=\'0\'>目的地</option>");
document.writeln("                    <option value=\'1\'>景点名称</option>");
document.writeln("                </select>");
document.writeln("                <input class=\'search-text\' type=\'text\' value=\'目的地或景区名称\'>");
document.writeln("                <div class=\'header-button\'>");
document.writeln("                    <input type=\'submit\' value=\'搜索\'>");
document.writeln("                </div>");
document.writeln("            </form>");
document.writeln("        </div>");
document.writeln("    </div>");
document.writeln("</header>");
document.writeln("<!-- 导航模块大图 -->");
document.writeln("<div class=\'navigation-module\'>");
document.writeln("    <div class=\'nav\'>");
document.writeln("        <div class=\'container\'>");
document.writeln("            <ul class=\'navUl\'></ul>");
document.writeln("        </div>");
document.writeln("    </div>");
document.writeln("</div>");
document.writeln("</body>");
document.writeln("</html>");